services:
  - type: web
    name: kerala-konishtt
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_ENV
        value: production
